services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres-data:
